spring:
  application:
    name: config-server
  profiles:
    active: git
#    active: native  # reading from file system
  cloud:
    config:
      server:
        native:
        git:
#          search-location: classpath:/config
         uri: https://github.com/rom201/ticketing-project-microservices-config-r
         default-label: main
         username: rom201
         password: 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   #can be token
#          '{cipher}11c1a0eb4421592f4d4913fa52971a70896067b7f9b033d56420bac609acee8d4e910f1241c11244dd2cec54156f0ff0efdea2c189fe7fc13f36e058fce30415'
#      fail-fast: true

#encrypt:
#  key: cydeo

server:
  port: 8888
